# ==========================================
# SECRETS.TOML (CONFIGURAÇÃO LOCAL)
# Atenção: Este arquivo contém dados reais e NÃO deve ser "comitado" no Git.
# ==========================================

# --- URLs AMBIENTE HOMOLOGAÇÃO ---
HOM_AUTH_PROJ = "https://q537lek385.execute-api.us-east-1.amazonaws.com/hom"
HOM_SENSOR_ALARM = "https://90wzien1dj.execute-api.us-east-1.amazonaws.com/hom"
HOM_WEBHOOK_ONU = "https://hom-eyon.lightera.com/api/webhook/externalEvent/"
HOM_ONU_SEARCH_BASE = "https://2dlkxsqhv2.execute-api.us-east-1.amazonaws.com"
HOM_OTDR_LIST = "https://lw04f3up60.execute-api.us-east-1.amazonaws.com"
HOM_OTDR_ALARM_BASE = "https://i8wjirfgu4.execute-api.us-east-1.amazonaws.com"

# --- URLs AMBIENTE DEV ---
DEV_AUTH_PROJ = "https://7w3isln6ej.execute-api.us-east-1.amazonaws.com/dev"
DEV_SENSOR_ALARM = "https://4xnev42un4.execute-api.us-east-1.amazonaws.com/dev"
DEV_WEBHOOK_ONU = "https://dev-eyon.lightera.com/api/webhook/externalEvent/"
DEV_ONU_SEARCH_BASE = "https://2dlkxsqhv2.execute-api.us-east-1.amazonaws.com"
DEV_OTDR_LIST = "https://lw04f3up60.execute-api.us-east-1.amazonaws.com"
DEV_OTDR_ALARM_BASE = "https://i8wjirfgu4.execute-api.us-east-1.amazonaws.com"

# --- URLs AMBIENTE PROD ---
PROD_AUTH_PROJ = "https://q7gg4s5wd3.execute-api.us-east-1.amazonaws.com/prod"
PROD_SENSOR_ALARM = "https://fs0ud7u5fk.execute-api.us-east-1.amazonaws.com/prod"
PROD_WEBHOOK_ONU = "https://eyon.lightera.com/api/webhook/externalEvent/"
PROD_ONU_SEARCH_BASE = "https://2dlkxsqhv2.execute-api.us-east-1.amazonaws.com"
PROD_OTDR_LIST = "https://lw04f3up60.execute-api.us-east-1.amazonaws.com"
PROD_OTDR_ALARM_BASE = "https://i8wjirfgu4.execute-api.us-east-1.amazonaws.com"

# --- TENANTS PADRÃO ---
DEFAULT_TENANT_ID = "e59a751c-1077-444f-9699-ce3f5e251114"
DEFAULT_TENANT_ONU = "ed7bd924-8ceb-4c26-8fbf-b984f7bd8fa9"

# --- DADOS FIXOS DO OTDR ---
OTDR_SOURCE_IP = "172.27.129.228:51860"
OTDR_RTU_IP = "172.27.129.228"